-- Fix user_accounts table schema
CREATE TABLE IF NOT EXISTS public.user_accounts (
    user_email TEXT PRIMARY KEY,
    deriv_api_token TEXT,
    deriv_account_id TEXT,
    broker_type TEXT DEFAULT 'deriv',
    broker_credentials JSONB,
    currency TEXT DEFAULT 'USD',
    locked_at TIMESTAMP WITH TIME ZONE,
    evaluation_started_at TIMESTAMP WITH TIME ZONE,
    start_balance DECIMAL,
    account_tier TEXT DEFAULT 'standard',
    account_size DECIMAL DEFAULT 10000,
    challenge_status TEXT DEFAULT 'active' CHECK (challenge_status IN ('active', 'passed', 'failed')),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.user_accounts ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own account" 
ON public.user_accounts FOR SELECT 
USING (auth.jwt() ->> 'email' = user_email);

CREATE POLICY "Users can update their own account" 
ON public.user_accounts FOR UPDATE 
USING (auth.jwt() ->> 'email' = user_email);

-- Table for trading stats (for Dashboard)
CREATE TABLE IF NOT EXISTS public.trading_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT REFERENCES public.user_accounts(user_email) ON DELETE CASCADE,
    balance DECIMAL NOT NULL,
    equity DECIMAL NOT NULL,
    daily_pnl DECIMAL DEFAULT 0,
    status TEXT DEFAULT 'active',
    last_trade_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for trading_states
ALTER TABLE public.trading_states ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own trading state" 
ON public.trading_states FOR SELECT 
USING (auth.jwt() ->> 'email' = user_email);
